name: Daily link-history email
on:
  workflow_dispatch:            # Enable manual invocation for testing
  schedule:
    - cron: "0 20 * * *"        # 6am daily (AEST)

jobs:
  Send-Email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: pip freeze
      - run: python daily_pinboard.py
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
          PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}

      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Your Pinboard Daily 5"
          html_body: file://email.html
          from: ${{ secrets.EMAIL }}
          to: ${{ secrets.EMAIL }}
